pipeline {
    agent any
    
    parameters {
        choice(name: 'action', choices: 'create\nrollback', description: 'Create/rollback of the deployment')
        string(name: 'ImageName', description: "Name of the docker build", defaultValue: "kubernetes-configmap-reload")
        string(name: 'ImageTag', description: "Docker tag", defaultValue: "v1")
        string(name: 'AppName', description: "Name of the Application", defaultValue: "kubernetes-configmap-reload")
        string(name: 'docker_repo', description: "Docker repository", defaultValue: "praveensingam1994")
    }
    
    tools {
        maven 'maven3'
    }
    
    stages {
        stage('Git-Checkout') {
            when { expression { params.action == 'create' } }
            steps {
                git branch: 'main',
                    url: 'https://github.com/DEVOPS-WITH-WEB-DEV/spring-cloud-kubernetes.git'
            }
        }

        stage('Build-Maven') {
            when { expression { params.action == 'create' } }
            steps {
                dir("${params.AppName}") {
                    sh 'mvn clean package'
                }
            }
        }

        stage("DockerBuild and Push") {
            when { expression { params.action == 'create' } }
            steps {
                dir("${params.AppName}") {
                    sh "docker build -t ${params.docker_repo}/${params.ImageName}:${params.ImageTag} ."
                    sh "docker push ${params.docker_repo}/${params.ImageName}:${params.ImageTag}"
                }
            }
        }

        stage("Docker-CleanUP") {
            when { expression { params.action == 'create' } }
            steps {
                sh "docker rmi ${params.docker_repo}/${params.ImageName}:${params.ImageTag} || true"
            }
        }

        stage("Ansible Setup") {
            when { expression { params.action == 'create' } }
            steps {
                sh "ansible-playbook ${WORKSPACE}/kubernetes-configmap-reload/server_setup.yml"
            }
        }

        stage("Create deployment") {
            when { expression { params.action == 'create' } }
            steps {
                sh "kubectl create -f ${WORKSPACE}/kubernetes-configmap-reload/kubernetes-configmap.yml"
            }
        }

        stage("wait_for_pods") {
            steps {
                sh 'sleep 300'
            }
        }

        stage("rollback deployment") {
            steps {
                sh """
                    kubectl delete deploy ${params.AppName} || true
                    kubectl delete svc ${params.AppName} || true
                """
            }
        }
    }
}
